{ pkgs, lib, ... }:
let
  rimeConfig = ../../dotfiles/rime/default.custom.yaml;
  rimeDict = ../../dotfiles/rime/my.dict.yaml;
  rimeIce = ../../dotfiles/rime/rime_ice.custom.yaml;
  rime-data = import ../../graphic/software/rime-data.nix {
    inherit pkgs;
  };
in
{
  imports = [ ../../common/home.nix ];

  home.file = {
    "Library/Application Support/Code/User/settings.json".source =
      import ../../graphic/home/vscode.nix
        { inherit pkgs; };

    ".p10k.zsh".source = lib.mkForce ../../dotfiles/.p10k.simple.zsh;

    "Library/Rime/default.custom.yaml".source = rimeConfig;
    "Library/Rime/my.dict.yaml".source = rimeDict;
    "Library/Rime/rime_ice.custom.yaml".source = rimeIce;
    # https://github.com/ryan4yin/nix-config/blob/main/home/darwin/rime-squirrel.nix
    "Library/Rime" = {
      source = "${
        pkgs.symlinkJoin {
          name = "squirrel-rime-data";
          paths = rime-data;
          postBuild = ''
            mkdir -p $out/share/rime-data

            # Ensure default.yaml exists
            [ -e "$out/share/rime-data/default.yaml" ] || touch "$out/share/rime-data/default.yaml"
          '';
        }
      }/share/rime-data";
      recursive = true;
      # overwrite possible existing data dynamically generated by squirrel
      # https://github.com/nix-community/home-manager/blob/release-23.05/modules/lib/file-type.nix#L101-L111
      force = true;
    };
    "Library/Rime/squirrel.yaml".source = "${pkgs.rime-ice.src}/squirrel.yaml";
    "Library/Rime/squirrel.custom.yaml".source = ../../dotfiles/rime/squirrel.custom.yaml;
  };

  programs.kitty = {
    enable = true;
    font.name = "JetBrainsMono Nerd Font Mono";
    shellIntegration.enableZshIntegration = true;
    themeFile = "Catppuccin-Frappe";
    extraConfig = ''
      background_opacity 0.8
      wayland_titlebar_color background
      map ctrl+c copy_or_interrupt
      map ctrl+v paste_from_clipboard
    '';
  };
}
