{
  inputs,
  lib,
  pkgs,
  ...
}:
let
  rimeConfig = ../../dotfiles/rime/default.custom.yaml;
  rimeDict = ../../dotfiles/rime/my.dict.yaml;
  rimeIce = ../../dotfiles/rime/rime_ice.custom.yaml;
  dirmngrConfig =
    lib.generators.toKeyValue
      {
        mkKeyValue =
          key: value: if lib.isString value then "${key} ${value}" else lib.optionalString value key;
        listsAsDuplicateKeys = true;
      }
      {
        keyserver = "hkps://keyserver.ubuntu.com";
        disable-ipv6 = true;
      };
  rime-data = import ../../graphic/software/rime-data.nix {
    inherit pkgs;
  };
in
{
  imports = [
    ../../common/home.nix
    inputs.nix-index-database.homeModules.nix-index
  ];

  programs.nix-index.enable = true;

  programs.zsh = {
    enable = true;
    initContent = ''
      source ~/.p10k.zsh
    '';
    history = {
      extended = true;
      save = 999999;
      size = 999999;
    };
  };

  programs.git = {
    enable = true;
    package = pkgs.gitFull;
    signing.format = "openpgp";
    settings = {
      user = {
        name = "Cryolitia PukNgae";
        email = "cryolitia@mercallure.com";
      };
      core.autocrlf = "input";
      sendemail = {
        smtpServer = "localhost";
        smtpServerPort = 25;
      };
      pull.ff = "only";
    };
  };

  programs.gh = {
    enable = true;
    gitCredentialHelper.enable = true;
  };

  home.file = {
    "Library/Application Support/Code/User/settings.json".source =
      import ../../graphic/home/vscode.nix
        { inherit pkgs; };

    ".p10k.zsh".source = lib.mkForce ../../dotfiles/.p10k.simple.zsh;
    ".config/hyfetch.json".source = ../../dotfiles/hyfetch.json;
    ".gnupg/dirmngr.conf".text = dirmngrConfig;

    "Library/Rime/default.custom.yaml".source = rimeConfig;
    "Library/Rime/my.dict.yaml".source = rimeDict;
    "Library/Rime/rime_ice.custom.yaml".source = rimeIce;
    # https://github.com/ryan4yin/nix-config/blob/main/home/darwin/rime-squirrel.nix
    "Library/Rime" = {
      source = "${
        pkgs.symlinkJoin {
          name = "squirrel-rime-data";
          paths = rime-data;
          postBuild = ''
            mkdir -p $out/share/rime-data

            # Ensure default.yaml exists
            [ -e "$out/share/rime-data/default.yaml" ] || touch "$out/share/rime-data/default.yaml"
          '';
        }
      }/share/rime-data";
      recursive = true;
      # overwrite possible existing data dynamically generated by squirrel
      # https://github.com/nix-community/home-manager/blob/release-23.05/modules/lib/file-type.nix#L101-L111
      force = true;
    };
    "Library/Rime/squirrel.yaml".source = "${pkgs.rime-ice.src}/squirrel.yaml";
    "Library/Rime/squirrel.custom.yaml".source = ../../dotfiles/rime/squirrel.custom.yaml;
  };

  programs.kitty = {
    enable = true;
    font.name = "JetBrainsMono Nerd Font Mono";
    shellIntegration.enableZshIntegration = true;
    themeFile = "Catppuccin-Frappe";
    extraConfig = ''
      background_opacity 0.8
      wayland_titlebar_color background
      map ctrl+c copy_or_interrupt
      map ctrl+v paste_from_clipboard
    '';
  };

  programs.btop = {
    enable = true;
    settings = {
      color_theme = "TTY";
      theme_background = false;
    };
  };

  programs.gpg = {
    enable = true;
    settings = lib.mkForce {
      ask-cert-level = true;
      keyserver-options = [
        "no-self-sigs-only"
        "no-import-clean"
      ];
      armor = true;
    };
  };
}
